### ISSUE TITLE
Add support for Windows and Mac 

### ISSUE THREAD

**Issue by msankhala** [wick3dr0se/fetch.sh#52]
Add support for Mac and Windows if this is in plan.

**Comment by SaintFenix** [comment]
Windows will be exceptionally difficult as this project is written in bash. 

Which Windows indirectly supports through cygwin and WSL2, but not natively.

Mac Support should be more doable however, I did a quick download and attempted a run on my Mac:

![image](https://user-images.githubusercontent.com/29680981/143890103-32cdb934-9231-4dd0-88bd-45557ea44929.png)

We've got quite a way to go on that side, due to the ancient version of bash being used on MacOS. This screenshot was taken on Version 10.15.1.

**Comment by wick3dr0se** [comment]
We are working on Windows support through WSL. GPU should work now with @SimoneSalzano's PR 60ecea58062521f928837e50b11774592e4f9eb0

Mac seems like it'll be a bit tricky since echo -e "\e \e \e \e" spits out just \e's. If you know of a way to resolve this that doesn't conflict with Linux I would love to make the changes! After I get a stable package produced for this we will start focusing on broadening the compatibility. We have to figure out many different file paths for Mac to get it's specs and a decent way to get terminal name without pstree

**Comment by saintphaenixos** [comment]
I've put in a pull request for basic Mac compatibility, here is it running on my Mac Mini:

Hostname does work, but censored for privacy:
![image](https://user-images.githubusercontent.com/25014799/144138966-b2e153d6-6acc-4a28-bdf4-8e2737548250.png)

Windows compatibility with Cygwin / WSL2 is going to require testers for both.

I think that should be a separate issue opened up.

**Comment by SaintFenix** [comment]
Can confirm on my Mac Pro:

![image](https://user-images.githubusercontent.com/29680981/144155392-0360a820-26f7-4246-b157-5c43b5798c66.png)

Swap is working, I just don't have any at the moment, as it's generated dynamically.

**Comment by wick3dr0se** [comment]
Can one of you do a pull on alpha and test the latest commit? I cleaned the code just a bit. 

Any way to shorten that swap output and add tabbing to arch ~, shell ~, theme ~ and swap ~? Maybe we could just get total swap size so we can print 2 swaps if found like otherwise done

**Comment by SaintFenix** [comment]
Here's my current output:

![image](https://user-images.githubusercontent.com/29680981/144159465-a3ef8757-c3c0-4e0f-afbd-7fee0b6cef38.png)

spacing seems to have taken a hit.

**Comment by wick3dr0se** [comment]
Try now, I just pushed a commit that should fix that gapping.

**Comment by SaintFenix** [comment]
Getting there:

![image](https://user-images.githubusercontent.com/29680981/144161058-61a4870c-35af-4f3f-b951-623154bf7f10.png)

**Comment by wick3dr0se** [comment]
I removed the redundant Catalina on os ~ Just need to gap arch and ram looks like

**Comment by wick3dr0se** [comment]
I did move that ram down with swap line like it is for Linux but that swap line is a bit excessive so its gonna shoot over a lot

**Comment by SaintFenix** [comment]
I think we're very close now: 

![image](https://user-images.githubusercontent.com/29680981/144161627-df4ac482-e223-4075-9c16-49c43f31b9bb.png)

Only ram doesn't make a lot of sense, as I'm not using 48GB of my 128GB.

Appreciate your fast iteration here.

**Comment by wick3dr0se** [comment]
May have to keep RAM line seperate like that till we can find a good alternative to get swap without so much output. Do you have another way to measure the usage to compare? Not sure how to fix that RAM output tho. You're still welcome to make PR. I don't mind reviewing it. I always enjoy learning something from contributions anyway!

**Comment by saintphaenixos** [comment]
Ah, it was being talked about here too as it was in pull #55.

I can do some work to get the usage numbers down to just the used, which is probably the one number we want for swap.

I'm also going to put together a different pull request for RAM, as I'm not a fan of how it's displaying right now.

But otherwise we're like 95% of the way there.

**Comment by wick3dr0se** [comment]
@saintphaenixos has made several commits to make Mac compatible and it should work functionally now. I will close this issue per #56. We need to focus on building support for Windows through WSL
